const fs = require("fs");
const path = require("path");
const assert = require("assert");

const appJs = fs.readFileSync(path.join(__dirname, "..", "src", "renderer", "app.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(__dirname, "..", "src", "renderer", "index.html"), "utf8");

assert.ok(appJs.includes("focus-running"));
assert.ok(appJs.includes("break-ready"));
assert.ok(appJs.includes("break-running"));
assert.ok(appJs.includes("interrupted"));
assert.ok(appJs.includes("task-completed"));
assert.ok(appJs.includes("settleFocusForCompletedTask(task)"));
assert.ok(appJs.includes("focusTrackedStatuses"));
assert.ok(appJs.includes("focusSessionMinutes(session)"));
assert.ok(appJs.includes("renderFocusHistory(task)"));
assert.ok(appJs.includes("buildFocusHistoryRows(sessions)"));
assert.ok(appJs.includes("focusPanelOpenId"));
assert.ok(appJs.includes("toggleFocusPanel"));
assert.ok(appJs.includes("shouldShowPanel"));
assert.ok(appJs.includes("focusPanel: document.querySelector"));
assert.ok(appJs.includes("handleInterruptReason"));
assert.ok(!appJs.includes("prompt("));
assert.ok(appJs.includes("confirmOtherInterrupt"));
assert.ok(appJs.includes("button.dataset.interruptKind || button.dataset.reason"));
assert.ok(appJs.includes("row.count > 1"));
assert.ok(appJs.includes("priority: \"important-urgent\""));
assert.ok(appJs.includes("formatCompactMinuteText(totalMinutes)"));
assert.ok(appJs.includes("new Date(session.focusEndsAt).getTime() <= now"));
assert.ok(appJs.includes("taskTitleSnapshot"));
assert.ok(indexHtml.includes("focusBar"));
assert.ok(indexHtml.includes("focusPanel"));
assert.ok(indexHtml.includes("openFocusPanel"));
assert.ok(indexHtml.includes("focus-toggle-button"));
assert.ok(indexHtml.includes("focusHistory"));
assert.ok(indexHtml.includes("data-reason"));
assert.ok(indexHtml.includes("data-interrupt-kind=\"other\""));
assert.ok(indexHtml.includes("interruptOtherDetail"));
assert.ok(indexHtml.includes("confirmOtherInterrupt"));

console.log("OK: focus timer state machine, interruption detail, and grouped history are present.");
